class Variable:
    __STR__ = "STR"
    __INTEGER__ = "INTEGER"
    __BOOLEAN__ = "BOOLEAN"
    __FLOAT__ = "FLOAT"
    __DATE__ = "DATE"
    __DATETIME__ = "DATETIME"
    __PRIMARYKEY__ = "PRIMARY KEY"
    __FOREIGNKEY__ = "FOREIGN KEY"
    __UNIQUE__ = "UNIQUE"
